# Generated by Django 4.0.5 on 2022-07-10 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aparteman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr', models.CharField(max_length=150, verbose_name='تیتر')),
                ('status_buy', models.CharField(choices=[('برای خرید', 'برای خرید'), ('برای رهن و اجاره', 'برای رهن و اجاره')], default='برای خرید', max_length=50, verbose_name='برای خرید/رهن و اجاره')),
                ('gheymat', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('gheymat_rahn', models.PositiveIntegerField(default=0, verbose_name='قیمت رهن')),
                ('gheymat_ejare', models.PositiveIntegerField(default=0, verbose_name='قیمت اجاره')),
                ('locations', models.TextField(verbose_name='ادرس اپارتمان')),
                ('sanad', models.CharField(choices=[('شش دانگ', 'شش دانگ'), ('مشاع', 'مشاع'), ('اصلاحات ارضی', 'اصلاحات ارضی')], default='شش دانگ', max_length=32, verbose_name='نوع سند')),
                ('andaze', models.PositiveSmallIntegerField(verbose_name='متراژ')),
                ('tabage', models.CharField(max_length=2, verbose_name='طبقه')),
                ('tedad_tabaghe', models.PositiveSmallIntegerField(verbose_name='تعداد طبقه')),
                ('tedad_vahed_tabaghe', models.PositiveSmallIntegerField(verbose_name='تعداد واحد در هر طبقه')),
                ('tedad_otagh', models.CharField(max_length=2, verbose_name='تعداد اتاق')),
                ('tedad_dastshoe', models.PositiveSmallIntegerField(verbose_name='تعداد سرویس بهداشتی')),
                ('sal_sakht', models.PositiveSmallIntegerField(verbose_name='چند سال ساخت')),
                ('ghabel_moaveze', models.BooleanField(default=False, verbose_name='قابل معاوضه؟')),
                ('tozihat_karbar', models.TextField(verbose_name='توضیحات کاربر')),
                ('tozihat_khososy', models.TextField(blank=True, null=True, verbose_name='توضیحات خصوصی')),
                ('map_1', models.TextField(blank=True, null=True, verbose_name='نقشه گوگل')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس اصلی')),
                ('upload_time', models.DateField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('vise', models.BooleanField(default=False, verbose_name='ویژه؟')),
                ('active', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('nevisande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'اپارتمان',
                'verbose_name_plural': 'اپارتمان ها',
                'ordering': ['-upload_time'],
            },
        ),
    ]
