# Generated by Django 4.0.4 on 2022-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_tabage_aparteman_tabaghe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparteman',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='micro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='sahel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='sigary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='system_garmayeshi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='tahvie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='trass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aparteman',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
