# Generated by Django 4.0.4 on 2022-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_aparteman_balcony_aparteman_bed_aparteman_internet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='sal_sakht',
            field=models.CharField(choices=[('0-5', '0-5'), ('5-10', '5-10'), ('10-20', '10-20'), ('20+', '20+')], default='0-5', max_length=10),
        ),
    ]
