# Generated by Django 4.0.4 on 2022-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_aparteman_sal_sakht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='parking',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
