# Generated by Django 4.0.4 on 2022-07-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_aparteman_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='andaze',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='aparteman',
            name='tabaghe',
            field=models.PositiveIntegerField(max_length=2, verbose_name='طبقه'),
        ),
    ]
