# Generated by Django 4.0.5 on 2022-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_aparteman_tabaghe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vilae',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
