# Generated by Django 4.0.5 on 2022-07-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_vilae_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vilae',
            name='parking',
        ),
        migrations.AlterField(
            model_name='aparteman',
            name='parking',
            field=models.CharField(max_length=2),
        ),
    ]
