# Generated by Django 4.0.5 on 2022-07-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_zamin_image_vilae_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparteman_images',
            old_name='image',
            new_name='images',
        ),
    ]
