# Generated by Django 4.0.4 on 2022-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_vilae_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilae',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
    ]
