# Generated by Django 4.0.5 on 2022-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_vilae_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='aparteman',
            name='parking',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='vilae',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
    ]
