# Generated by Django 4.0.5 on 2022-07-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_aparteman_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparteman',
            name='parking',
        ),
    ]
