# Generated by Django 4.0.5 on 2022-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_aparteman_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparteman',
            name='parking',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
