# Generated by Django 4.0.5 on 2022-07-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_aparteman_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilae',
            name='parking',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
