# Generated by Django 4.0.5 on 2022-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_vilae_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilae',
            name='sanad',
            field=models.CharField(choices=[('شش دانگ', 'شش دانگ'), ('مشاع', 'مشاع'), ('اصلاحات ارضی', 'اصلاحات ارضی')], default='شش دانگ', max_length=32, verbose_name='نوع سند'),
        ),
    ]
