# Generated by Django 4.0.4 on 2022-07-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_vilae_sanad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='vilae',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
    ]
