# Generated by Django 4.0.6 on 2022-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_aparteman_status_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressApa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
