# Generated by Django 4.0.6 on 2022-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_ipaddressapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressVilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
