# Generated by Django 4.0.6 on 2022-07-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_ipaddressvilla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddressVilla',
        ),
    ]
