# Generated by Django 4.0.6 on 2022-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_delete_ipaddressvilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressVilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='aparteman',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='posts.ipaddressapa'),
        ),
        migrations.AddField(
            model_name='vilae',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='posts.ipaddressvilla'),
        ),
    ]
