# Generated by Django 4.0.5 on 2022-07-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, unique=True)),
                ('Email', models.EmailField(max_length=350)),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='تلفن اول')),
                ('phone_2', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='تلفن دوم')),
                ('semat', models.CharField(default='مشاور فروش', max_length=100, verbose_name='سمت')),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('code_posty', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('insta', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('whats_app', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('telegram', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('about_me', models.TextField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'اطلاعات کارکنان',
            },
        ),
    ]
