# Generated by Django 4.0.4 on 2022-07-09 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_informations', '0003_alter_admininformation_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformation',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
