# Generated by Django 4.0.4 on 2022-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_informations', '0004_alter_admininformation_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininformation',
            name='full_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='insta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن اول'),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='telegram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='whats_app',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
