# Generated by Django 4.0.6 on 2022-07-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_informations', '0007_rename_ipaddress_ipaddressaparteman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddressAparteman',
        ),
    ]
